name: Android Build and Release

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.STORE_FILE_BASE64 }}" | base64 --decode > my-release-key.jks

      - name: Build and Sign APK
        run: |
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=my-release-key.jks \
                                    -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} \
                                    -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
                                    -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Verify Signed APK (optional)
        run: apksigner verify app/build/outputs/apk/release/app-release.apk

      - name: Create and push a new tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag v0.0.${{ github.run_number }}
          git push origin v0.0.${{ github.run_number }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
          tag_name: v0.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
